/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;


import main.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import static java.awt.SystemColor.text;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.JOptionPane;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import static javax.management.Query.value;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.util.Calendar;
import javax.swing.JPanel;

/**
 *
 * @author Ibaad Mohammed
 */
public class FormPanel extends javax.swing.JPanel {

    private Component frame;

    /**
     * Creates new form FormPanel
     */
    private JPanel bottomPanel;
    private Component root;
    public FormPanel(JPanel inputPanel) {
        initComponents();
        this.bottomPanel = inputPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButton = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        lastnameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        firstnameField = new javax.swing.JTextField();
        lastnameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        MessagePanel = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        photoButton = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        patientTypeLabel = new javax.swing.JLabel();
        typeCombo = new javax.swing.JComboBox<>();
        appointmentdateLabel = new javax.swing.JLabel();
        appointmentDate = new com.toedter.calendar.JDateChooser();

        mainPanel.setBackground(new java.awt.Color(0, 204, 204));

        titleLabel.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("PATIENT REGISTRATION FORM");

        firstnameLabel.setText("First Name:");

        lastnameLabel.setText("Last Name:");

        ageLabel.setText("Age :");

        genderLabel.setText("Gender:");

        ageField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageFieldKeyPressed(evt);
            }
        });

        genderButton.add(maleButton);
        maleButton.setText("Male");
        maleButton.setActionCommand("Male User");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        genderButton.add(femaleButton);
        femaleButton.setText("Female");
        femaleButton.setActionCommand("Female User");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        emailLabel.setText("Mail id :");

        messageLabel.setText("Message :");

        messageArea.setColumns(20);
        messageArea.setRows(5);
        MessagePanel.setViewportView(messageArea);

        photoButton.setText("Upload Photo");
        photoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoButtonActionPerformed(evt);
            }
        });

        photoLabel.setText("Photo :");

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        patientTypeLabel.setText("Patient Type :");

        typeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "In-Patient", "Out-Patient" }));
        typeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboActionPerformed(evt);
            }
        });

        appointmentdateLabel.setText("Date of Appointment :-");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnameLabel)
                            .addComponent(lastnameLabel)
                            .addComponent(ageLabel)
                            .addComponent(emailLabel)
                            .addComponent(photoLabel)
                            .addComponent(patientTypeLabel)
                            .addComponent(appointmentdateLabel)
                            .addComponent(messageLabel)
                            .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(photoButton))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(firstnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                                            .addComponent(lastnameField)
                                            .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(MessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(maleButton)
                                            .addComponent(femaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addComponent(appointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(176, 176, 176)))))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(4, 4, 4)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleButton)
                    .addComponent(genderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femaleButton)
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageLabel)
                    .addComponent(MessagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientTypeLabel)
                    .addComponent(typeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentdateLabel)
                    .addComponent(appointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoButton)
                    .addComponent(photoLabel))
                .addGap(38, 38, 38)
                .addComponent(submitButton)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ageFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageFieldKeyPressed
        try{
            int Age = Integer.parseInt(ageField.getText());
            ageField.setForeground(Color.black);

        }
        catch(Exception e){
            ageField.setForeground(Color.red);
        }// TODO add your handling code here:
    }//GEN-LAST:event_ageFieldKeyPressed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed

    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleButtonActionPerformed

    private String Filepath;
    private void photoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoButtonActionPerformed
        JFileChooser file = new JFileChooser();
        if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            try {
BufferedImage img = ImageIO.read(file.getSelectedFile());
Filepath = file.getSelectedFile().getAbsolutePath();
    Object edited_image = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
    
if (edited_image != null) {
    
ImageIcon icon = new ImageIcon((Image) edited_image);
photoLabel.setIcon(icon);
} else {
throw new Exception();
}
} catch (Exception ex) {
}
}

    }//GEN-LAST:event_photoButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        User newUser = new User();        
        newUser.setName( firstnameField.getText());
        newUser.setLname(lastnameField.getText());
        newUser.setAge( ageField.getText());
        newUser.setGender(genderButton.getSelection().getActionCommand());
        newUser.setEmail(emailField.getText());
        newUser.setMessage(messageArea.getText());
        newUser.setType(typeCombo.getSelectedItem().toString());
        SimpleDateFormat dFormat= new SimpleDateFormat("dd-MM-yyyy");
        newUser.setDate(dFormat.format(appointmentDate.getDate()));
        
        ViewPanel newViewPanel = new ViewPanel(newUser);
       bottomPanel.add(newViewPanel);
       CardLayout layout = (CardLayout) bottomPanel.getLayout();
       layout.next(bottomPanel);
       submitButton.addActionListener(e -> {
            // Here, check some condition (e.g., if a radio button is selected)
            boolean conditionMet = false;  // For the sake of this demo
            if (!conditionMet) {
                JOptionPane.showMessageDialog(frame, "Condition not met!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        submitButton.addActionListener(e -> {
            if (genderButton.getSelection() == null) {
                // No radio button is selected
                JOptionPane.showMessageDialog(frame, "Please select one of the options!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        if (firstnameField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "First Name is empty. Please enter some information.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else if  (lastnameField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Last Name is empty. Please enter some information.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else if  (ageField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Age is empty. Please enter some information.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else if (genderButton.getSelection() == null) {

            JOptionPane.showMessageDialog(frame, "Please select Gender", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (emailField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "E-Mail is empty. Please enter some information.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else if (messageArea.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Message is empty. Please enter some information.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        else if (typeCombo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please Select Patient Type", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else {
            Component rootPane = null;
            JOptionPane.showMessageDialog(rootPane, firstnameField.getText()+" "+lastnameField.getText()+" "+ageField.getText()+" "+genderButton.getSelection().getActionCommand()+" "+emailField.getText()+" "+messageArea.getText()+ " "+typeCombo.getSelectedItem().toString()+"  Date:"+appointmentDate.getDate()+" ", "User Information", HEIGHT,photoLabel.getIcon());
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void typeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboActionPerformed
        submitButton.addActionListener(e -> {
        });
    }//GEN-LAST:event_typeComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane MessagePanel;
    private javax.swing.JTextField ageField;
    private javax.swing.JLabel ageLabel;
    private com.toedter.calendar.JDateChooser appointmentDate;
    private javax.swing.JLabel appointmentdateLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.ButtonGroup genderButton;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel patientTypeLabel;
    private javax.swing.JButton photoButton;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JComboBox<String> typeCombo;
    // End of variables declaration//GEN-END:variables
}
